package maver.talkingonstations.httpapi

import maver.talkingonstations.llm.ToolInterface
import maver.talkingonstations.llm.dto.ApiSettings
import maver.talkingonstations.llm.dto.Message
import maver.talkingonstations.llm.dto.ModelSettings

interface HttpApiInterface {
    var supportsToolCalling: Boolean

    /**
     * Part of a suspended function chain.
     * When the chat ui scope is destroyed, a cancellation will walk down the chain,
     * the HTTP API is responsible for forwarding the cancellation to the http client.
     *
     * Network calls must run on [kotlinx.coroutines.Dispatchers.IO]
     *
     * @link https://github.com/gildor/kotlin-coroutines-okhttp#usage
     * @link https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-i-o.html
     *
     * Loaded via [HttpApiLoader] and needs to be discoverable.
     * @see /data/config/tos/Api.csv
     *
     * Must return a [Message] object with role
     *  - INFO Shown the user, not sent back to the llm. Error messages, service notices.
     *  - ASSISTANT Text generated by the model
     *  - USER Text written by the user
     *
     * @see maver.talkingonstations.chat.ChatRoles
     *
     * Should return [maver.talkingonstations.httpapi.exception.HttpApiRequestException] on unrecoverable errors
     * and a message object with the INFO role on soft errors.
     *
     * @param apiSettings - The api settings used for the call
     * @param instructions - System message block
     * @param messages - A list of message blocks, the chat history
     * @param model - Model id and its settings
     */
    suspend fun send(
        apiSettings: ApiSettings,
        instructions: String,
        messages: List<Message>,
        model: ModelSettings,
        tools: List<ToolInterface>,
    ): Message

    /**
     * Must return an identifier that lines up with the identifier provided by [maver.talkingonstations.TosSettings]
     */
    fun getName(): String
}
